### ISSUE TITLE
Should plugins have access to ops.json

### ISSUE THREAD

**Issue by caojohnny** [TridentSDK/TridentSDK#82]
Rather than wrapping with Player and using a list obtained from Server, should plugins be able to be trusted to have access to the Config, or should they break consistency by having to create their own config object for ops.json?

**Comment by yannicklamprecht** [comment]
Why they need access to the ops.yml?
Instead add a possibility to setOP in PermissionOwner. 

opped() is available
So add
setOpped(boolean)

**Comment by caojohnny** [comment]
Both methods are already available.

The point is should players who aren't on the server have the ability to be opped? Does this make necessary an OfflinePlayer for example?

**Comment by caojohnny** [comment]
Leaving it as no, they should not have direct access.

**Comment by yannicklamprecht** [comment]
Direct access no. Access using an offlinePlayer yes. The problem is that developer are able to destroy the format of the file using direct access.

**Comment by caojohnny** [comment]
Agreed, good point.
